README.md
package.json
src/dataregistry.ts
src/index.ts
yarn.lock

Add labels to dataregistry

---

src/index.ts

Redirected to `console.error` for now.

Add error messages for snippet command

---

src/dataset.ts
src/exception.tsx

adds basic validation of dataset metadata on the frontend

---

jupyterlab_hdf/util.py
release.py

<s>I also added some rough and minimalist tests but still have to figure out how to test this properly</s>:
EDIT: working on a separate PR for tests. It might be simpler than what I thought.

Adding `id`, `attributeCount` and `childrenCount` to the meta endpoint

---

jupyterlab_hdf/baseHandler.py

fixes #61: update `get` handler sig with builtin `async` keyword and `@web.authenticated`

---

jupyterlab_hdf/api/api.yaml

Updated YAML with new meta fields

---

jupyterlab_hdf/api/api.yaml

I messed up the description fields in #63. This should fix them.

Fix description fields of YAML

---

jupyterlab_hdf/api/api.yaml
jupyterlab_hdf/util.py

Removes `id` from meta response

---

README.md
jupyterlab_hdf/data.py

Added optional support for additional compression filters

---

jupyterlab_hdf/tests/test_data.py
jupyterlab_hdf/tests/test_meta.py
jupyterlab_hdf/util.py

See https://github.com/h5py/h5py/issues/279 for some context.
Also added endpoints tests for scalar datasets.

Added basic support of empty datasets (`H5S_NULL` shape in HDF5)

---

src/AttributeViewer.tsx
src/index.ts
style/AttributeViewer.css
style/index.css

Fix #28 
**Context menu action in the HDF file browser:**
**Display in the main area:**

Added basic display of attributes as context menu action

---

.github/workflows/binder-on-pr.yml
.gitignore
binder/environment.yml
binder/postBuild
binder/requirements.txt
setup.py

adds a workflow that will add a comment with a binder badge that links to a binder that will let anyone try the PR out easily

add github workflow to produce a binder badge for all PRs

---

style/AttributeViewer.css

Fixed AttributeViewer text not visible in dark mode

---

jupyterlab_hdf/api/api.yaml

Fixed api yaml with new meta endpoint

---

jupyterlab_hdf/api/api.yaml
jupyterlab_hdf/attrs.py
jupyterlab_hdf/baseHandler.py
jupyterlab_hdf/tests/test_attrs.py
jupyterlab_hdf/util.py

Follow-up of #87: having the attr metadata allows for selective fetching of attribute values

/hdf/attrs can be used to request attributes by name

---

.github/workflows/binder-on-pr.yml

See https://github.com/jupyterlab/jupyterlab-git/commit/f0b492a9973ee26c3b42b77730adc1aa0144b159#diff-0eb70f36e049fe37b66ad232dd95bcf6ea50a80105a93a62f7461740f727d2fd

Fix binder-on-pr job permissions

---

src/AttributeViewer.tsx
src/complex.ts
src/dataset.ts
src/exception.tsx
src/hdf.ts
src/index.ts
src/toolbar.tsx

**Old:**
**New:**
Also fixed a few _Missing return type_ warnings

Fixed display of complex attributes

---

jupyterlab_hdf/tests/test_meta.py
jupyterlab_hdf/util.py

Meta endpoint returns children metadata rather than count

---

jupyterlab_hdf/api/api.yaml

Updated API with new meta endpoint

---

jupyterlab_hdf/baseHandler.py

Raise 404 instead of 500 when entity not found

---

src/AttributeViewer.tsx
style/AttributeViewer.css

Fix https://github.com/jupyterlab/jupyterlab-hdf5/issues/133#issuecomment-1440543831

Make Attribute table scrollable

---

jupyterlab_hdf/tests/test_data.py
jupyterlab_hdf/util.py
src/dataset.ts

Display 1d data as column

---

src/browser.ts

Fixes https://github.com/jupyterlab/jupyterlab-hdf5/issues/140

Only patch the listing node of the file browser
